# Generated by Django 4.2.5 on 2023-10-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo2app',
            name='de',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
